<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6.0;net8.0;net10.0</TargetFrameworks>
		<LangVersion>8.0</LangVersion>
		<SignAssembly>True</SignAssembly>
		<AssemblyOriginatorKeyFile>sixnet.snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Sixnet" Version="2.1.1" />
	  <PackageReference Include="StackExchange.Redis" Version="2.13.17" />
	</ItemGroup>

</Project>
